### ISSUE TITLE
Scan URL example for Beatus vir

### ISSUE THREAD

**Issue by craigsapp** [WolfgangDrescher/lassus-geistliche-psalmen#1]
The link:

```
!!!YOR: https://mdz-nbn-resolving.de/details:bsb00075346
```

links to the URL:

```
https://www.digitale-sammlungen.de/en/details/bsb00075346
```

which in turn has a thumbnail for the cover of the scan:

<img width="1220" alt="Screen Shot 2022-03-05 at 1 22 37 PM" src="https://user-images.githubusercontent.com/3487289/156900290-470010d1-be84-45a6-a306-8c96fb3bcbe1.png">

clicking brings you to the full scan of the front cover:

https://www.digitale-sammlungen.de/en/view/bsb00075346?page=,1

<img width="1220" alt="Screen Shot 2022-03-05 at 1 24 51 PM" src="https://user-images.githubusercontent.com/3487289/156900341-77358330-f0bc-4e52-96f4-a4488ada1b89.png">

And then here are the pages in the scan for Beatus vir (not conveniently adjacent since this is three different part books):

https://www.digitale-sammlungen.de/en/view/bsb00075346?page=11
https://www.digitale-sammlungen.de/en/view/bsb00075346?page=71
https://www.digitale-sammlungen.de/en/view/bsb00075346?page=127

It would be useful to encode these three links into the digital score as well (for much faster access to the musical content that the digital score is based on):

```
!!!URL-scan: https://www.digitale-sammlungen.de/en/view/bsb00075346?page=11 Cantus
!!!URL-scan: https://www.digitale-sammlungen.de/en/view/bsb00075346?page=71 Tenor
!!!URL-scan: https://www.digitale-sammlungen.de/en/view/bsb00075346?page=127 Bassus
```

After the URL in this reference record, there is an optional title for the URL, such as "Cantus" for the first scan link.   VHV detects such records, and creates a list of links on the left side of the first toolbar for them:

<img width="1344" alt="Screen Shot 2022-03-05 at 1 41 29 PM" src="https://user-images.githubusercontent.com/3487289/156900814-1a3dc062-944d-45da-96cf-7574aece86b2.png">

<img width="450" alt="Screen Shot 2022-03-05 at 1 41 39 PM" src="https://user-images.githubusercontent.com/3487289/156900817-2c8ffd21-839b-4050-bcd6-d93f6d801ed6.png">

If you mouse over one of the scan icons, the title of the URL will be displayed as a tooltip:

<img width="266" alt="Screen Shot 2022-03-05 at 1 42 12 PM" src="https://user-images.githubusercontent.com/3487289/156900840-d4ba33cb-1cbe-42dd-a971-f6229d10f2f6.png">

And clicking on the scan icon will open the webpage for the scan (in this case directly to the Cantus music):

<img width="1344" alt="Screen Shot 2022-03-05 at 1 42 59 PM" src="https://user-images.githubusercontent.com/3487289/156900853-2acceddd-7905-49aa-9917-278982641250.png">

**Comment by craigsapp** [comment]
The cantus part starting is weird:

<img width="994" alt="Screen Shot 2022-03-05 at 1 50 56 PM" src="https://user-images.githubusercontent.com/3487289/156901014-28372065-d6e4-4795-a5dc-34e8c72f6986.png">

The opening looks like it is colored, but the transcription is not (and I don't know why/if it should be colored).

Also note a special fliter called `kernview` which is used to view selected parts, but still allow graphical editing in the SVG image (using `extract -k 3` for the same score will not allow graphical editing since the data is filtered before it is rendered in verovio, causing the xml:ids to be messed up compared to the original digital score in the text editor).

<img width="752" alt="Screen Shot 2022-03-05 at 1 54 26 PM" src="https://user-images.githubusercontent.com/3487289/156901075-6d0ae1ab-ef70-44ae-9aa2-ddf640179fb3.png">

The coloration seems to be an error, because beside alignment with the other parts, there are two quarter notes (semi-minims) in the third measure that are not colored (according to the transcription), but they look like the previous "colored minims".

**Comment by craigsapp** [comment]
Zooming in on the notes in the Cantus part, it looks like they were filled in by hand with ink:

<img width="474" alt="Screen Shot 2022-03-05 at 9 24 07 PM" src="https://user-images.githubusercontent.com/3487289/156910441-29de71fb-b89a-45c8-9a5c-2a40cead7ce8.png">

So maybe someone's kid got ahold of the book and was trying to fill in all of the notes....

**Comment by WolfgangDrescher** [comment]
> It would be useful to encode these three links into the digital score as well (for much faster access to the musical content that the digital score is based on)

Okay, I added them to the source. Sadly there does not seem to be a (localization neutral) permalink for the direct links to the pages. But without the locale it does seem to redirect to your language (https://www.digitale-sammlungen.de/view/bsb00075346?page=11). Since I'm not sure if this will work permanently I just stick to the german link for my project.

>The cantus part starting is weird

Yes I also noticed this. But I think I encoded it correctly since otherwise it does not fit to the other voices. "Modern” editions on IMSLP (https://imslp.org/wiki/Teutsche_Psalmen_(Lassus,_Orlande_de)) seem to transcribe it the same way. So as you said I also think the coloration seems to be an error.

Is there a way to express this difference in humdrum? Semantically or maybe with a note.

**Comment by WolfgangDrescher** [comment]
> So maybe someone's kid got ahold of the book and was trying to fill in all of the notes....

That's a nice theory :-) .

There are multiple digital representation of this pice on digitale-sammlungen.de. I just checked another one and it seems to be correct there: https://www.digitale-sammlungen.de/de/view/bsb00072990?page=11. I will link to this version as soon as I find the other voices. I just found Cantus for now with the other digital representation.

**Comment by craigsapp** [comment]
> Is there a way to express this difference in humdrum? Semantically or maybe with a note.

The best would be with a note.  One possibility would be using `!!!ONB:`:

```
!!!ONB: Starting notes of the Cantus part have been filled in by hand with an ink pen.
```

I use this form the most, since they are easy to locate later with the command-line command:

```bash
grep ONB *.krn
```


Or a non-formatted comment (which I would place above the first note that is filled in):

```
!! Starting notes of the Cantus part have been filed in by hand with an ink pen.
```

There is also a local comment method (other spines would have single `!`):

```
! notes filled in with ink pen in source
```


In any case, there is not much semantic information in this observation since it is clearly not from the original print nor a correction afterwards but rather doodling.

----------------

I have implemented a "sic" system for Humdrum files, which is a special form of correction, but in this case it would not be useful:

https://doc.verovio.humdrum.org/filter/sic

**Comment by WolfgangDrescher** [comment]
Would something like this be a valid syntax?

```
!!!YOR: https://mdz-nbn-resolving.de/details:bsb00075346
!!!YOR-alt: https://mdz-nbn-resolving.de/details:bsb00075346
!!!YOO: München, Bayerische Staatsbibliothek
!!!URL-scan: https://www.digitale-sammlungen.de/de/view/bsb00075346?page=11 Cantus
!!!URL-scan: https://www.digitale-sammlungen.de/de/view/bsb00075346?page=71 Tenor
!!!URL-scan: https://www.digitale-sammlungen.de/de/view/bsb00075346?page=127 Bassus
!!!URL-scan-alt: https://www.digitale-sammlungen.de/de/view/bsb00072990?page=11 Cantus
!!!IIIF: https://api.digitale-sammlungen.de/iiif/presentation/v2/bsb00075346/manifest
```

In general, how free am I to add my own extensions to existing reference records? E.g. something like `!!!URL-scan-alt`, `!!!YOR-alt`, `!!!OTL-incipit`, `!!!voices-OPR` or similar.

**Comment by craigsapp** [comment]
Yes, that looks good.  

The general rule is that official reference records use capital letters, numbers and sometimes `#` (and maybe `_`).  For non-standard or user-defined records, lower case letters should be used (preferably no spaces in reference record keys or other non-letter characters).

`URL` is a semi-standard (it is not in the official list at https://www.humdrum.org/reference-records/index.html), but it makes sense to treat it as an official one.   I am putting IIIF in capitals although it is not in the official list (and it has four letters, while all standard ones have three) &mdash; and an "I" often looks similar to a "!", so maybe `!!!iiif:` might have been a better choice...   This record will be important for cross-application support, so that is probably why I decided to make it capital (so currently semi-official since I have not added it to the official list).

A dash following the reference record means a "subcategorization":

<img width="999" alt="Screen Shot 2022-03-08 at 7 02 06 AM" src="https://user-images.githubusercontent.com/3487289/157264438-c806e0e0-3a18-4471-825e-16688a87063c.png">

There is no official list of subcategorizations, so you can make up your own (but if you make up your own, then they should be in lower case).

> `!!!URL-scan-alt`

Adding multiple categorizations (or subcategorizations as in this case) is no problem.

---------------

Regarding:

```
!!!URL-scan: https://www.digitale-sammlungen.de/de/view/bsb00075346?page=11 Cantus
!!!URL-scan-alt: https://www.digitale-sammlungen.de/de/view/bsb00072990?page=11 Cantus
```

I don't think that `alt` is too necessary here and you could put the quailfication in the optional text description after the link:

```
!!!URL-scan: https://www.digitale-sammlungen.de/de/view/bsb00075346?page=11 Cantus
!!!URL-scan: https://www.digitale-sammlungen.de/de/view/bsb00072990?page=11 Cantus (without doodles)
```



One reason is that I don't think that VHV will show a link if there is the extra `-alt` added?   In any case I would suggest making the `alt` link the primary `URL-scan` entry, since that is the one without the filled in notes.  And otherwise, this is the same print (in theory they should be identical, although there could be corrections in one if they are from different printings).

A more sophisticated sub categorization would be useful if you have multiple source editions used to create the Humdrum digital score.  In that case there is usually a "principle" source that most of the digital score is based on, with occasionally corrections from other sources.

Something like this would be useful in such situations

```
!!!URL-scan-ms1a: https://www.digitale-sammlungen.de/de/view/bsb00075346?page=11 Cantus (ms1a)
!!!URL-scan-ms1b: https://www.digitale-sammlungen.de/de/view/bsb00072990?page=11 Cantus (ms1b)
```

where `ms1a` is a tag for some manuscript (or print) called `ms1a` (or `1a`) and the `ms1b` is for manuscript `ms1b` (or `1b`).
