### ISSUE TITLE
IIIF encoding in Humdrum files

### ISSUE THREAD

**Issue by craigsapp** [WolfgangDrescher/lassus-geistliche-psalmen#2]
IIIF image information can be stored in Humdrum digital scores.   Here is a demo of how to do it (I have not had time to add to the VHV documentation yet).

(1) Copy the IIIF manifest, such as 
      https://api.digitale-sammlungen.de/iiif/presentation/v2/bsb00075346/manifest
from the website with the scanned images, such as this one:
      https://www.digitale-sammlungen.de/en/view/bsb00075346?page=11

(2) Got to the NIFC annotator website:
    https://pl-wnifc.github.io/nifc-iiif-annotator

Click on the blue circle with the white plus sign at the top left corner of the page to add a new manifest entry:

<img width="414" alt="Screen Shot 2022-03-05 at 4 00 58 PM" src="https://user-images.githubusercontent.com/3487289/156903669-aa150650-dc73-441c-bb83-afbed3d53260.png">

Click on "+ ADD RESOURCE" button at the bottom right corner of the page:

<img width="231" alt="Screen Shot 2022-03-05 at 4 01 14 PM" src="https://user-images.githubusercontent.com/3487289/156903671-46634d05-4823-4d85-9c35-fa1c456b1b45.png">

And then paste the IIIF link copied previously, which in the example case is:

https://api.digitale-sammlungen.de/iiif/presentation/v2/bsb00075346/manifest

Then click the blue "ADD" button to load the entry onto the website.
 
<img width="1059" alt="Screen Shot 2022-03-05 at 4 02 22 PM" src="https://user-images.githubusercontent.com/3487289/156903690-5fc1edc4-cd5e-45d8-a46d-7732641aa45c.png">

Click on entry in the manifest list that you want to extract bounding boxes from, and it will load into the annotator:

<img width="1158" alt="Screen Shot 2022-03-05 at 4 02 38 PM" src="https://user-images.githubusercontent.com/3487289/156903699-5e55bff8-2970-4276-8782-cf69859aad73.png">

Go to the desired page of music from gallery view:

<img width="575" alt="Screen Shot 2022-03-05 at 4 03 03 PM" src="https://user-images.githubusercontent.com/3487289/156903710-0b735a34-2776-45ee-9ce1-f8c5756f1631.png">

And select the desired page from the list of page thumbnails:

<img width="894" alt="Screen Shot 2022-03-05 at 4 03 33 PM" src="https://user-images.githubusercontent.com/3487289/156903719-06b13237-501d-4ccc-b5e1-9a78b65bda5b.png">

(3) To extract bounding boxes from page, click on the square gray plus button in the Annotation section of the page (which is displayed if you click on the word balloon icon highlighted in blue in the following example:

<img width="345" alt="Screen Shot 2022-03-05 at 4 05 15 PM" src="https://user-images.githubusercontent.com/3487289/156903749-24917935-2c8f-433e-b194-13db25bab7f4.png">

After clicking on the gray plus button, a control panel should appear on the right side of the image:

<img width="1290" alt="Screen Shot 2022-03-05 at 4 05 50 PM" src="https://user-images.githubusercontent.com/3487289/156903760-03287c99-6fff-45d7-b112-5891e7506cfd.png">

Click on the square icon just underneath the the gray cursor button:

<img width="224" alt="Screen Shot 2022-03-05 at 4 06 18 PM" src="https://user-images.githubusercontent.com/3487289/156903771-1e8da172-e388-4b81-ad67-9a362abca088.png">

Now you can draw boxes in the image, and each box will cause an entry to appear in the text box in the annotation tool:

<img width="1290" alt="Screen Shot 2022-03-05 at 4 08 28 PM" src="https://user-images.githubusercontent.com/3487289/156903795-ae03c9a8-70e4-4159-984d-12fc5aa6804a.png">

Then copy the text that is added in the text box on the right, by pressing the blue Copy button:

```
*xywh:75,57,2846,552
*xywh:104,598,2787,427
*xywh:140,985,2769,445
*xywh:87,1424,2805,404
*xywh:98,1793,2775,499
```

These are the five bounding boxes for the systems of the example page.   As a side-effect of pressing the `Copy` button, the text will disappear from the text area (by design since it is not possible to edit the text, so it needs to be cleared out for processing the next page).  

Take note of the scan number from the bottom of the interface, which is `11` in this case:

<img width="178" alt="Screen Shot 2022-03-05 at 4 13 42 PM" src="https://user-images.githubusercontent.com/3487289/156903891-0d8ea681-fd7a-4a2d-b7ea-342da2a013fb.png">

And add it as a postfix parameter to the bounding box information:

```
*xywh-#11:75,57,2846,552
*xywh-#11:104,598,2787,427
*xywh-#11:140,985,2769,445
*xywh-#11:87,1424,2805,404
*xywh-#11:98,1793,2775,499
```

There is a page label on the right: `(0011)`.  This can also be used (as long as it is unique in the list of pages)

```
*xywh-(0011):75,57,2846,552
*xywh-(0011):104,598,2787,427
*xywh-(0011):140,985,2769,445
*xywh-(0011):87,1424,2805,404
*xywh-(0011):98,1793,2775,499
```

Then add these interpretations to the score (in the `**kern` columns for the part at the starting point in the music for each bounding box).

Once the bounding boxes are encoded in the score, you can double click on any note in VHV, and it will open the image for that region of the music in a separate pop-out window:

<img width="1619" alt="Screen Shot 2022-03-05 at 9 32 23 PM" src="https://user-images.githubusercontent.com/3487289/156910761-10303026-cba0-4e0a-ac6a-06b158ded4e7.png">

The image is downloaded at 100% resolution, and you should be able to toggle fitting the image to the window and max pixel view by clicking on the image in the window:

<img width="1443" alt="Screen Shot 2022-03-05 at 9 39 50 PM" src="https://user-images.githubusercontent.com/3487289/156910794-7bf5fe74-e5cc-4ee2-aaaf-93b9464f95fc.png">

Currently there is not conversion of the IIIF information to MEI, but if you want it, you can create a mock-translation of how the IIIF info should be embedded in the MEI conversion.

**Comment by craigsapp** [comment]
Here is a full demo of IIIF bounding box embedding in a Humdrum score:

https://verovio.humdrum.org/?file=https%3A%2F%2Fdata.nifc.humdrum.org%2F15xx%3A298.krn

<img width="1352" alt="Screen Shot 2022-03-05 at 9 58 08 PM" src="https://user-images.githubusercontent.com/3487289/156911293-8e88cc5f-fe50-44c7-9f8c-c93fad63eea7.png">

You can click on any note, and the image of the staff on which the note comes from in the source will be displayed.

**Comment by craigsapp** [comment]
Also, here is the first Github URL for 150 Psalm settings by Mikołaj Gomółka that I used to prototype the IIIF data embedding (this is the same Psalm 1 as your test file, published in the same decade, but in Polish and four parts, and mostly homophonic):

https://github.com/pl-wnifc/humdrum-polish-scores/blob/main/pl-wn/kern/pl-wn--sd-xvi-qu-273--001_gomolka-mikolaj--melodiae-na-psalterz-polski-i-szczesliwy-ktory-nie-byl-miedzy-zlymi-w-radzie.krn

For easier interaction with VHV, here is the link for the first psalm:
https://verovio.humdrum.org/?file=https%3A%2F%2Fdata.nifc.humdrum.org%2F15xx%3A206.krn

(No. 2 ends in `207.krn` for example).

**Comment by craigsapp** [comment]
Also I forgot to mention that the manifest needs to be stored in a reference record:

```
!!!IIIF: https://api.digitale-sammlungen.de/iiif/presentation/v2/bsb00075346/manifest
```

-----------------------

Related to the filled-in notes discussed in issue #1, I need to allow for multiple manifests in the same score.  Probably it would be like this:

```
!!!IIIF-c: https://api.digitale-sammlungen.de/iiif/presentation/v2/bsb00075346/manifest
!!!IIIF-t: https://api.digitale-sammlungen.de/iiif/presentation/v2/bsb00075347/manifest
!!!IIIF-b: https://api.digitale-sammlungen.de/iiif/presentation/v2/bsb00075348/manifest
```

Where each manifest is given a tag (`c`, `t` and `b`), and then the `*xywh` interpretations would have a similar tag to indicate which manifest the bounding box info refers to:

```
*xywh-c-#11:104,598,2787,427
*xywh-t-#11:87,1424,2805,404
*xywh-b-#11:98,1793,2775,499
```

This could also allow encoding multiple simultaneous bounding boxes, one for each source, but how to easily select the source you want to see when double-clicking on a note in VHV would need more thinking (such as a drop-down box to select a particular source).

**Comment by craigsapp** [comment]
Also I now remember there is a dedicated repository for the psalm settings:

https://github.com/pl-wnifc/mikolaj-gomolka-psalms

but these are mostly just for testing, with any updates (none that I really know of) done in the repository mentioned above.

**Comment by WolfgangDrescher** [comment]
This is really nice! Thank you for this hint. A keyboard shortcut would be nice, since it can be a bit fiddly to double click on the notes.

> Currently there is not conversion of the IIIF information to MEI, but if you want it, you can create a mock-translation of how the IIIF info should be embedded in the MEI conversion.

That's something for the future for me. First I want to get to know Humdrum better before I venture into MEI.

**Comment by craigsapp** [comment]
> A keyboard shortcut would be nice, since it can be a bit fiddly to double click on the notes.

It would be difficult to have a keyboard shortcut, since each staff (as in your repertory) have a different source image...

The main problem is that half-notes and larger durations have a hollow center that cannot be clicked on.  One solution would be to have a transparent box/circle placed underneath the noteheads so that clicking in the center of hollow notes would be able to select them.

A general solution to this problem is solved by Voronoy regions, where a click on the SVG image would select the closest notehead even if not clicking directly on the notehead:

https://github.com/d3/d3-delaunay
https://observablehq.com/@mbostock/the-delaunays-dual
https://en.wikipedia.org/wiki/Voronoi_diagram

**Comment by WolfgangDrescher** [comment]
> It would be difficult to have a keyboard shortcut, since each staff (as in your repertory) have a different source image...

I meant it you have a note highlighted and then navigate with the arrow keys.

**Comment by craigsapp** [comment]
> I meant it you have a note highlighted and then navigate with the arrow keys.

OK, although at some point you still have to click on a note 😉
