### ISSUE TITLE
OTL notes

### ISSUE THREAD

**Issue by craigsapp** [WolfgangDrescher/lassus-geistliche-psalmen#3]
For the title information:

```
!!!OTL: Beatus vir
!!!OTL@DE: Selig zu preisen ist der mann
```

I would interpret this to mean:

* The primary title of the work is `Beatus vir` (in an undefined language).
*  The title translation into German is `Selig zu preisen ist der mann`

The second statement is not quite right:  Selig... is not a translation of _Beatus vir_, is it?  I would call this an "incipit" or "incipit text", since it is the beginning of the lyrical text rather than the title of the composition.

I do not think there is a reference record to exactly describe it, but I would probably suggest:

```
!!!OTL-incipit@DE: Selig zu preisen ist der mann
```

(but if you don't want to be that fussy, it is not a problem).

Also, `@DE` means "translated into German", but there is also `@@DE` which means the original language (in the source edition) is German.

The title record:

```
!!!OTL: Beatus vir
```

Could also be encoded as:

```
!!!OTL@@LAT: Beatus vir
```

Meaning that the language of the title is in Latin (as found in the source due to the double `@@`).

**Comment by WolfgangDrescher** [comment]
Then the most correct encoding would probably be

```
!!!OTL@@LAT: Beatus vir
!!!OTL-incipit@@DE: Selig zu preisen ist der mann
```

since the title is originally in latin and the incipit is originally in german. If the syntax of `OTL-incipit@@DE` is valid.

**Comment by craigsapp** [comment]
Yes, that is good.  I cannot remember the two letter code for Latin, so I used the 3 letter code:

https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

So `@@LA` can also be used.  `@@DEU` for the three letter German one.

The langauge qualifiers are probably not of great use.   One use is to search for words in the titles, and you can then filter the searches by language.   The other use for them would be to display titles on a website in the user's langauge.


```
!!!OTL: Beatus vir
```

Implies that Beatus vir is in the original language (but not necessarily guaranteed), and the original language is unspecified.
