### ISSUE TITLE
AGN note

### ISSUE THREAD

**Issue by craigsapp** [WolfgangDrescher/lassus-geistliche-psalmen#5]
I usually encoded separate genre categories:

```
!!!AGN: Psalm, Tricinium
```

with semicolon separators:

```
!!!AGN: Psalm; Tricinium
```

This is not mentioned in the documentation, I notice:

https://www.humdrum.org/reference-records

But it is implied by how multiple values are given in other reference records in the documentation:

<img width="476" alt="Screen Shot 2022-03-05 at 10 27 27 PM" src="https://user-images.githubusercontent.com/3487289/156911992-b2be4a8c-87f8-4ea6-8831-adb452c0c37e.png">

<img width="589" alt="Screen Shot 2022-03-05 at 10 28 10 PM" src="https://user-images.githubusercontent.com/3487289/156912002-3d408592-36a8-47a3-8fbe-fbd3949dc85d.png">

**Comment by WolfgangDrescher** [comment]
Off topic but just came to my mind fixing this… I saw that in the JRP there are often reference records for informations about number of voices.

E.g. in https://github.com/josquin-research-project/Jos/blob/main/Jos0301a-Missa_Ave_maris_stella-Kyrie.krn

```
!!!voices: 4
!!!voices-OPR: 4
```

What are they actually useful for?

**Comment by craigsapp** [comment]
`!!!voices: 4` means that the score in the file has four voices in the original composition.   If there is a missing part, then this value will be 4, but there will only be three `**kern` spines for the remaining volices.  In other words, the purpose of this record is so that I can separate music with missing parts when doing harmonic analyses of the data.


```voices-OPR: 4``` means that the number of voices in the mass is 4 (considering all sections, which are in separate files).

```voices-OPR: 4-5``` would mean that there are some sections in 4 voices and others in 5.  

```voices-OPR: 4-(5)``` would mean that the sections are mostly in 4 voices, but there are some subsections that expanded out to 5 voices (such as Bassus I and Bassus II parts).
